version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - ENVIRONMENT=production
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    environment:
      - VITE_API_BASE_URL=/api/v1
    depends_on:
      - backend

  db:
    image: arangodb:3.11
    env_file:
      - backend/.env
    ports:
      - "8529:8529"
    volumes:
      - quranref_data:/var/lib/arangodb3

volumes:
  quranref_data:
