services:
  arangodb:
    image: arangodb:3.8.9
    container_name: quranref_arangodb
    env_file:
      - backend/.env
    ports:
      - "8530:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
      # dockerfile: Dockerfile
      target: app-build
    container_name: quranref
    command: poetry run fastapi dev quranref/main.py --host 0.0.0.0 --port 7000
    env_file:
      - backend/.env
    environment:
      - AM_I_DOCKERIZED=1
    volumes:
      - .:/code
    ports:
      - "7000:7000"

volumes:
  arangodb_data:
