services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    container_name: quranref
    command: poetry run fastapi dev quranref/main.py --host 0.0.0.0 --port 7000
    volumes:
      - .:/app
      # - /app/.venv
    ports:
      - "7000:7000"
