#surah_info = [
#    #[start, ayas, order, rukus, name, tname, ename, type]
#    [],  #empty list to occupy index 0 so that surah indexes and order match
#    [0, 7, 5, 1, 'الفاتحة', "Al-Faatiha", 'The Opening', 'Meccan'],
#    [7, 286, 87, 40, 'البقرة', "Al-Baqara", 'The Cow', 'Medinan'],
#    [293, 200, 89, 20, 'آل عمران', "Aal-i-Imraan", 'The Family of Imraan', 'Medinan'],
#    [493, 176, 92, 24, 'النساء', "An-Nisaa", 'The Women', 'Medinan'],
#    [669, 120, 112, 16, 'المائدة', "Al-Maaida", 'The Table', 'Medinan'],
#    [789, 165, 55, 20, 'الأنعام', "Al-An'aam", 'The Cattle', 'Meccan'],
#    [954, 206, 39, 24, 'الأعراف', "Al-A'raaf", 'The Heights', 'Meccan'],
#    [1160, 75, 88, 10, 'الأنفال', "Al-Anfaal", 'The Spoils of War', 'Medinan'],
#    [1235, 129, 113, 16, 'التوبة', "At-Tawba", 'The Repentance', 'Medinan'],
#    [1364, 109, 51, 11, 'يونس', "Yunus", 'Jonas', 'Meccan'],
#    [1473, 123, 52, 10, 'هود', "Hud", 'Hud', 'Meccan'],
#    [1596, 111, 53, 12, 'يوسف', "Yusuf", 'Joseph', 'Meccan'],
#    [1707, 43, 96, 6, 'الرعد', "Ar-Ra'd", 'The Thunder', 'Medinan'],
#    [1750, 52, 72, 7, 'ابراهيم', "Ibrahim", 'Abraham', 'Meccan'],
#    [1802, 99, 54, 6, 'الحجر', "Al-Hijr", 'The Rock', 'Meccan'],
#    [1901, 128, 70, 16, 'النحل', "An-Nahl", 'The Bee', 'Meccan'],
#    [2029, 111, 50, 12, 'الإسراء', "Al-Israa", 'The Night Journey', 'Meccan'],
#    [2140, 110, 69, 12, 'الكهف', "Al-Kahf", 'The Cave', 'Meccan'],
#    [2250, 98, 44, 6, 'مريم', "Maryam", 'Mary', 'Meccan'],
#    [2348, 135, 45, 8, 'طه', "Taa-Haa", 'Taa-Haa', 'Meccan'],
#    [2483, 112, 73, 7, 'الأنبياء', "Al-Anbiyaa", 'The Prophets', 'Meccan'],
#    [2595, 78, 103, 10, 'الحج', "Al-Hajj", 'The Pilgrimage', 'Medinan'],
#    [2673, 118, 74, 6, 'المؤمنون', "Al-Muminoon", 'The Believers', 'Meccan'],
#    [2791, 64, 102, 9, 'النور', "An-Noor", 'The Light', 'Medinan'],
#    [2855, 77, 42, 6, 'الفرقان', "Al-Furqaan", 'The Criterion', 'Meccan'],
#    [2932, 227, 47, 11, 'الشعراء', "Ash-Shu'araa", 'The Poets', 'Meccan'],
#    [3159, 93, 48, 7, 'النمل', "An-Naml", 'The Ant', 'Meccan'],
#    [3252, 88, 49, 8, 'القصص', "Al-Qasas", 'The Stories', 'Meccan'],
#    [3340, 69, 85, 7, 'العنكبوت', "Al-Ankaboot", 'The Spider', 'Meccan'],
#    [3409, 60, 84, 6, 'الروم', "Ar-Room", 'The Romans', 'Meccan'],
#    [3469, 34, 57, 3, 'لقمان', "Luqman", 'Luqman', 'Meccan'],
#    [3503, 30, 75, 3, 'السجدة', "As-Sajda", 'The Prostration', 'Meccan'],
#    [3533, 73, 90, 9, 'الأحزاب', "Al-Ahzaab", 'The Clans', 'Medinan'],
#    [3606, 54, 58, 6, 'سبإ', "Saba", 'Sheba', 'Meccan'],
#    [3660, 45, 43, 5, 'فاطر', "Faatir", 'The Originator', 'Meccan'],
#    [3705, 83, 41, 5, 'يس', "Yaseen", 'Yaseen', 'Meccan'],
#    [3788, 182, 56, 5, 'الصافات', "As-Saaffaat", 'Those drawn up in Ranks', 'Meccan'],
#    [3970, 88, 38, 5, 'ص', "Saad", 'The letter Saad', 'Meccan'],
#    [4058, 75, 59, 8, 'الزمر', "Az-Zumar", 'The Groups', 'Meccan'],
#    [4133, 85, 60, 9, 'غافر', "Al-Ghaafir", 'The Forgiver', 'Meccan'],
#    [4218, 54, 61, 6, 'فصلت', "Fussilat", 'Explained in detail', 'Meccan'],
#    [4272, 53, 62, 5, 'الشورى', "Ash-Shura", 'Consultation', 'Meccan'],
#    [4325, 89, 63, 7, 'الزخرف', "Az-Zukhruf", 'Ornaments of gold', 'Meccan'],
#    [4414, 59, 64, 3, 'الدخان', "Ad-Dukhaan", 'The Smoke', 'Meccan'],
#    [4473, 37, 65, 4, 'الجاثية', "Al-Jaathiya", 'Crouching', 'Meccan'],
#    [4510, 35, 66, 4, 'الأحقاف', "Al-Ahqaf", 'The Dunes', 'Meccan'],
#    [4545, 38, 95, 4, 'محمد', "Muhammad", 'Muhammad', 'Medinan'],
#    [4583, 29, 111, 4, 'الفتح', "Al-Fath", 'The Victory', 'Medinan'],
#    [4612, 18, 106, 2, 'الحجرات', "Al-Hujuraat", 'The Inner Apartments', 'Medinan'],
#    [4630, 45, 34, 3, 'ق', "Qaaf", 'The letter Qaaf', 'Meccan'],
#    [4675, 60, 67, 3, 'الذاريات', "Adh-Dhaariyat", 'The Winnowing Winds', 'Meccan'],
#    [4735, 49, 76, 2, 'الطور', "At-Tur", 'The Mount', 'Meccan'],
#    [4784, 62, 23, 3, 'النجم', "An-Najm", 'The Star', 'Meccan'],
#    [4846, 55, 37, 3, 'القمر', "Al-Qamar", 'The Moon', 'Meccan'],
#    [4901, 78, 97, 3, 'الرحمن', "Ar-Rahmaan", 'The Beneficent', 'Medinan'],
#    [4979, 96, 46, 3, 'الواقعة', "Al-Waaqia", 'The Inevitable', 'Meccan'],
#    [5075, 29, 94, 4, 'الحديد', "Al-Hadid", 'The Iron', 'Medinan'],
#    [5104, 22, 105, 3, 'المجادلة', "Al-Mujaadila", 'The Pleading Woman', 'Medinan'],
#    [5126, 24, 101, 3, 'الحشر', "Al-Hashr", 'The Exile', 'Medinan'],
#    [5150, 13, 91, 2, 'الممتحنة', "Al-Mumtahana", 'She that is to be examined', 'Medinan'],
#    [5163, 14, 109, 2, 'الصف', "As-Saff", 'The Ranks', 'Medinan'],
#    [5177, 11, 110, 2, 'الجمعة', "Al-Jumu'a", 'Friday', 'Medinan'],
#    [5188, 11, 104, 2, 'المنافقون', "Al-Munaafiqoon", 'The Hypocrites', 'Medinan'],
#    [5199, 18, 108, 2, 'التغابن', "At-Taghaabun", 'Mutual Disillusion', 'Medinan'],
#    [5217, 12, 99, 2, 'الطلاق', "At-Talaaq", 'Divorce', 'Medinan'],
#    [5229, 12, 107, 2, 'التحريم', "At-Tahrim", 'The Prohibition', 'Medinan'],
#    [5241, 30, 77, 2, 'الملك', "Al-Mulk", 'The Sovereignty', 'Meccan'],
#    [5271, 52, 2, 2, 'القلم', "Al-Qalam", 'The Pen', 'Meccan'],
#    [5323, 52, 78, 2, 'الحاقة', "Al-Haaqqa", 'The Reality', 'Meccan'],
#    [5375, 44, 79, 2, 'المعارج', "Al-Ma'aarij", 'The Ascending Stairways', 'Meccan'],
#    [5419, 28, 71, 2, 'نوح', "Nooh", 'Noah', 'Meccan'],
#    [5447, 28, 40, 2, 'الجن', "Al-Jinn", 'The Jinn', 'Meccan'],
#    [5475, 20, 3, 2, 'المزمل', "Al-Muzzammil", 'The Enshrouded One', 'Meccan'],
#    [5495, 56, 4, 2, 'المدثر', "Al-Muddaththir", 'The Cloaked One', 'Meccan'],
#    [5551, 40, 31, 2, 'القيامة', "Al-Qiyaama", 'The Resurrection', 'Meccan'],
#    [5591, 31, 98, 2, 'الانسان', "Al-Insaan", 'Man', 'Medinan'],
#    [5622, 50, 33, 2, 'المرسلات', "Al-Mursalaat", 'The Emissaries', 'Meccan'],
#    [5672, 40, 80, 2, 'النبإ', "An-Naba", 'The Announcement', 'Meccan'],
#    [5712, 46, 81, 2, 'النازعات', "An-Naazi'aat", 'Those who drag forth', 'Meccan'],
#    [5758, 42, 24, 1, 'عبس', "Abasa", 'He frowned', 'Meccan'],
#    [5800, 29, 7, 1, 'التكوير', "At-Takwir", 'The Overthrowing', 'Meccan'],
#    [5829, 19, 82, 1, 'الإنفطار', "Al-Infitaar", 'The Cleaving', 'Meccan'],
#    [5848, 36, 86, 1, 'المطففين', "Al-Mutaffifin", 'Defrauding', 'Meccan'],
#    [5884, 25, 83, 1, 'الإنشقاق', "Al-Inshiqaaq", 'The Splitting Open', 'Meccan'],
#    [5909, 22, 27, 1, 'البروج', "Al-Burooj", 'The Constellations', 'Meccan'],
#    [5931, 17, 36, 1, 'الطارق', "At-Taariq", 'The Morning Star', 'Meccan'],
#    [5948, 19, 8, 1, 'الأعلى', "Al-A'laa", 'The Most High', 'Meccan'],
#    [5967, 26, 68, 1, 'الغاشية', "Al-Ghaashiya", 'The Overwhelming', 'Meccan'],
#    [5993, 30, 10, 1, 'الفجر', "Al-Fajr", 'The Dawn', 'Meccan'],
#    [6023, 20, 35, 1, 'البلد', "Al-Balad", 'The City', 'Meccan'],
#    [6043, 15, 26, 1, 'الشمس', "Ash-Shams", 'The Sun', 'Meccan'],
#    [6058, 21, 9, 1, 'الليل', "Al-Lail", 'The Night', 'Meccan'],
#    [6079, 11, 11, 1, 'الضحى', "Ad-Dhuhaa", 'The Morning Hours', 'Meccan'],
#    [6090, 8, 12, 1, 'الشرح', "Ash-Sharh", 'The Consolation', 'Meccan'],
#    [6098, 8, 28, 1, 'التين', "At-Tin", 'The Fig', 'Meccan'],
#    [6106, 19, 1, 1, 'العلق', "Al-Alaq", 'The Clot', 'Meccan'],
#    [6125, 5, 25, 1, 'القدر', "Al-Qadr", 'The Power, Fate', 'Meccan'],
#    [6130, 8, 100, 1, 'البينة', "Al-Bayyina", 'The Evidence', 'Medinan'],
#    [6138, 8, 93, 1, 'الزلزلة', "Az-Zalzala", 'The Earthquake', 'Medinan'],
#    [6146, 11, 14, 1, 'العاديات', "Al-Aadiyaat", 'The Chargers', 'Meccan'],
#    [6157, 11, 30, 1, 'القارعة', "Al-Qaari'a", 'The Calamity', 'Meccan'],
#    [6168, 8, 16, 1, 'التكاثر', "At-Takaathur", 'Competition', 'Meccan'],
#    [6176, 3, 13, 1, 'العصر', "Al-Asr", 'The Declining Day, Epoch', 'Meccan'],
#    [6179, 9, 32, 1, 'الهمزة', "Al-Humaza", 'The Traducer', 'Meccan'],
#    [6188, 5, 19, 1, 'الفيل', "Al-Fil", 'The Elephant', 'Meccan'],
#    [6193, 4, 29, 1, 'قريش', "Quraish", 'Quraysh', 'Meccan'],
#    [6197, 7, 17, 1, 'الماعون', "Al-Maa'un", 'Almsgiving', 'Meccan'],
#    [6204, 3, 15, 1, 'الكوثر', "Al-Kawthar", 'Abundance', 'Meccan'],
#    [6207, 6, 18, 1, 'الكافرون', "Al-Kaafiroon", 'The Disbelievers', 'Meccan'],
#    [6213, 3, 114, 1, 'النصر', "An-Nasr", 'Divine Support', 'Medinan'],
#    [6216, 5, 6, 1, 'المسد', "Al-Masad", 'The Palm Fibre', 'Meccan'],
#    [6221, 4, 22, 1, 'الإخلاص', "Al-Ikhlaas", 'Sincerity', 'Meccan'],
#    [6225, 5, 20, 1, 'الفلق', "Al-Falaq", 'The Dawn', 'Meccan'],
#    [6230, 6, 21, 1, 'الناس', "An-Naas", 'Mankind', 'Meccan'],
#]

surah_info = [
	{},  # empty item so that indexes and surah number match
    {'arabic_name': 'الفاتحة',
    'english_name': 'Al-Faatiha',
    'nuzool_location': 'Meccan',
    'nuzool_order': 5,
    'rukus': 1,
    'starting_aya': 0,
    'total_ayas': 7,
    'translated_name': 'The Opening'},
    {'arabic_name': 'البقرة',
    'english_name': 'Al-Baqara',
    'nuzool_location': 'Medinan',
    'nuzool_order': 87,
    'rukus': 40,
    'starting_aya': 7,
    'total_ayas': 286,
    'translated_name': 'The Cow'},
    {'arabic_name': 'آل عمران',
    'english_name': 'Aal-i-Imraan',
    'nuzool_location': 'Medinan',
    'nuzool_order': 89,
    'rukus': 20,
    'starting_aya': 293,
    'total_ayas': 200,
    'translated_name': 'The Family of Imraan'},
    {'arabic_name': 'النساء',
    'english_name': 'An-Nisaa',
    'nuzool_location': 'Medinan',
    'nuzool_order': 92,
    'rukus': 24,
    'starting_aya': 493,
    'total_ayas': 176,
    'translated_name': 'The Women'},
    {'arabic_name': 'المائدة',
    'english_name': 'Al-Maaida',
    'nuzool_location': 'Medinan',
    'nuzool_order': 112,
    'rukus': 16,
    'starting_aya': 669,
    'total_ayas': 120,
    'translated_name': 'The Table'},
    {'arabic_name': 'الأنعام',
    'english_name': "Al-An'aam",
    'nuzool_location': 'Meccan',
    'nuzool_order': 55,
    'rukus': 20,
    'starting_aya': 789,
    'total_ayas': 165,
    'translated_name': 'The Cattle'},
    {'arabic_name': 'الأعراف',
    'english_name': "Al-A'raaf",
    'nuzool_location': 'Meccan',
    'nuzool_order': 39,
    'rukus': 24,
    'starting_aya': 954,
    'total_ayas': 206,
    'translated_name': 'The Heights'},
    {'arabic_name': 'الأنفال',
    'english_name': 'Al-Anfaal',
    'nuzool_location': 'Medinan',
    'nuzool_order': 88,
    'rukus': 10,
    'starting_aya': 1160,
    'total_ayas': 75,
    'translated_name': 'The Spoils of War'},
    {'arabic_name': 'التوبة',
    'english_name': 'At-Tawba',
    'nuzool_location': 'Medinan',
    'nuzool_order': 113,
    'rukus': 16,
    'starting_aya': 1235,
    'total_ayas': 129,
    'translated_name': 'The Repentance'},
    {'arabic_name': 'يونس',
    'english_name': 'Yunus',
    'nuzool_location': 'Meccan',
    'nuzool_order': 51,
    'rukus': 11,
    'starting_aya': 1364,
    'total_ayas': 109,
    'translated_name': 'Jonas'},
    {'arabic_name': 'هود',
    'english_name': 'Hud',
    'nuzool_location': 'Meccan',
    'nuzool_order': 52,
    'rukus': 10,
    'starting_aya': 1473,
    'total_ayas': 123,
    'translated_name': 'Hud'},
    {'arabic_name': 'يوسف',
    'english_name': 'Yusuf',
    'nuzool_location': 'Meccan',
    'nuzool_order': 53,
    'rukus': 12,
    'starting_aya': 1596,
    'total_ayas': 111,
    'translated_name': 'Joseph'},
    {'arabic_name': 'الرعد',
    'english_name': "Ar-Ra'd",
    'nuzool_location': 'Medinan',
    'nuzool_order': 96,
    'rukus': 6,
    'starting_aya': 1707,
    'total_ayas': 43,
    'translated_name': 'The Thunder'},
    {'arabic_name': 'ابراهيم',
    'english_name': 'Ibrahim',
    'nuzool_location': 'Meccan',
    'nuzool_order': 72,
    'rukus': 7,
    'starting_aya': 1750,
    'total_ayas': 52,
    'translated_name': 'Abraham'},
    {'arabic_name': 'الحجر',
    'english_name': 'Al-Hijr',
    'nuzool_location': 'Meccan',
    'nuzool_order': 54,
    'rukus': 6,
    'starting_aya': 1802,
    'total_ayas': 99,
    'translated_name': 'The Rock'},
    {'arabic_name': 'النحل',
    'english_name': 'An-Nahl',
    'nuzool_location': 'Meccan',
    'nuzool_order': 70,
    'rukus': 16,
    'starting_aya': 1901,
    'total_ayas': 128,
    'translated_name': 'The Bee'},
    {'arabic_name': 'الإسراء',
    'english_name': 'Al-Israa',
    'nuzool_location': 'Meccan',
    'nuzool_order': 50,
    'rukus': 12,
    'starting_aya': 2029,
    'total_ayas': 111,
    'translated_name': 'The Night Journey'},
    {'arabic_name': 'الكهف',
    'english_name': 'Al-Kahf',
    'nuzool_location': 'Meccan',
    'nuzool_order': 69,
    'rukus': 12,
    'starting_aya': 2140,
    'total_ayas': 110,
    'translated_name': 'The Cave'},
    {'arabic_name': 'مريم',
    'english_name': 'Maryam',
    'nuzool_location': 'Meccan',
    'nuzool_order': 44,
    'rukus': 6,
    'starting_aya': 2250,
    'total_ayas': 98,
    'translated_name': 'Mary'},
    {'arabic_name': 'طه',
    'english_name': 'Taa-Haa',
    'nuzool_location': 'Meccan',
    'nuzool_order': 45,
    'rukus': 8,
    'starting_aya': 2348,
    'total_ayas': 135,
    'translated_name': 'Taa-Haa'},
    {'arabic_name': 'الأنبياء',
    'english_name': 'Al-Anbiyaa',
    'nuzool_location': 'Meccan',
    'nuzool_order': 73,
    'rukus': 7,
    'starting_aya': 2483,
    'total_ayas': 112,
    'translated_name': 'The Prophets'},
    {'arabic_name': 'الحج',
    'english_name': 'Al-Hajj',
    'nuzool_location': 'Medinan',
    'nuzool_order': 103,
    'rukus': 10,
    'starting_aya': 2595,
    'total_ayas': 78,
    'translated_name': 'The Pilgrimage'},
    {'arabic_name': 'المؤمنون',
    'english_name': 'Al-Muminoon',
    'nuzool_location': 'Meccan',
    'nuzool_order': 74,
    'rukus': 6,
    'starting_aya': 2673,
    'total_ayas': 118,
    'translated_name': 'The Believers'},
    {'arabic_name': 'النور',
    'english_name': 'An-Noor',
    'nuzool_location': 'Medinan',
    'nuzool_order': 102,
    'rukus': 9,
    'starting_aya': 2791,
    'total_ayas': 64,
    'translated_name': 'The Light'},
    {'arabic_name': 'الفرقان',
    'english_name': 'Al-Furqaan',
    'nuzool_location': 'Meccan',
    'nuzool_order': 42,
    'rukus': 6,
    'starting_aya': 2855,
    'total_ayas': 77,
    'translated_name': 'The Criterion'},
    {'arabic_name': 'الشعراء',
    'english_name': "Ash-Shu'araa",
    'nuzool_location': 'Meccan',
    'nuzool_order': 47,
    'rukus': 11,
    'starting_aya': 2932,
    'total_ayas': 227,
    'translated_name': 'The Poets'},
    {'arabic_name': 'النمل',
    'english_name': 'An-Naml',
    'nuzool_location': 'Meccan',
    'nuzool_order': 48,
    'rukus': 7,
    'starting_aya': 3159,
    'total_ayas': 93,
    'translated_name': 'The Ant'},
    {'arabic_name': 'القصص',
    'english_name': 'Al-Qasas',
    'nuzool_location': 'Meccan',
    'nuzool_order': 49,
    'rukus': 8,
    'starting_aya': 3252,
    'total_ayas': 88,
    'translated_name': 'The Stories'},
    {'arabic_name': 'العنكبوت',
    'english_name': 'Al-Ankaboot',
    'nuzool_location': 'Meccan',
    'nuzool_order': 85,
    'rukus': 7,
    'starting_aya': 3340,
    'total_ayas': 69,
    'translated_name': 'The Spider'},
    {'arabic_name': 'الروم',
    'english_name': 'Ar-Room',
    'nuzool_location': 'Meccan',
    'nuzool_order': 84,
    'rukus': 6,
    'starting_aya': 3409,
    'total_ayas': 60,
    'translated_name': 'The Romans'},
    {'arabic_name': 'لقمان',
    'english_name': 'Luqman',
    'nuzool_location': 'Meccan',
    'nuzool_order': 57,
    'rukus': 3,
    'starting_aya': 3469,
    'total_ayas': 34,
    'translated_name': 'Luqman'},
    {'arabic_name': 'السجدة',
    'english_name': 'As-Sajda',
    'nuzool_location': 'Meccan',
    'nuzool_order': 75,
    'rukus': 3,
    'starting_aya': 3503,
    'total_ayas': 30,
    'translated_name': 'The Prostration'},
    {'arabic_name': 'الأحزاب',
    'english_name': 'Al-Ahzaab',
    'nuzool_location': 'Medinan',
    'nuzool_order': 90,
    'rukus': 9,
    'starting_aya': 3533,
    'total_ayas': 73,
    'translated_name': 'The Clans'},
    {'arabic_name': 'سبإ',
    'english_name': 'Saba',
    'nuzool_location': 'Meccan',
    'nuzool_order': 58,
    'rukus': 6,
    'starting_aya': 3606,
    'total_ayas': 54,
    'translated_name': 'Sheba'},
    {'arabic_name': 'فاطر',
    'english_name': 'Faatir',
    'nuzool_location': 'Meccan',
    'nuzool_order': 43,
    'rukus': 5,
    'starting_aya': 3660,
    'total_ayas': 45,
    'translated_name': 'The Originator'},
    {'arabic_name': 'يس',
    'english_name': 'Yaseen',
    'nuzool_location': 'Meccan',
    'nuzool_order': 41,
    'rukus': 5,
    'starting_aya': 3705,
    'total_ayas': 83,
    'translated_name': 'Yaseen'},
    {'arabic_name': 'الصافات',
    'english_name': 'As-Saaffaat',
    'nuzool_location': 'Meccan',
    'nuzool_order': 56,
    'rukus': 5,
    'starting_aya': 3788,
    'total_ayas': 182,
    'translated_name': 'Those drawn up in Ranks'},
    {'arabic_name': 'ص',
    'english_name': 'Saad',
    'nuzool_location': 'Meccan',
    'nuzool_order': 38,
    'rukus': 5,
    'starting_aya': 3970,
    'total_ayas': 88,
    'translated_name': 'The letter Saad'},
    {'arabic_name': 'الزمر',
    'english_name': 'Az-Zumar',
    'nuzool_location': 'Meccan',
    'nuzool_order': 59,
    'rukus': 8,
    'starting_aya': 4058,
    'total_ayas': 75,
    'translated_name': 'The Groups'},
    {'arabic_name': 'غافر',
    'english_name': 'Al-Ghaafir',
    'nuzool_location': 'Meccan',
    'nuzool_order': 60,
    'rukus': 9,
    'starting_aya': 4133,
    'total_ayas': 85,
    'translated_name': 'The Forgiver'},
    {'arabic_name': 'فصلت',
    'english_name': 'Fussilat',
    'nuzool_location': 'Meccan',
    'nuzool_order': 61,
    'rukus': 6,
    'starting_aya': 4218,
    'total_ayas': 54,
    'translated_name': 'Explained in detail'},
    {'arabic_name': 'الشورى',
    'english_name': 'Ash-Shura',
    'nuzool_location': 'Meccan',
    'nuzool_order': 62,
    'rukus': 5,
    'starting_aya': 4272,
    'total_ayas': 53,
    'translated_name': 'Consultation'},
    {'arabic_name': 'الزخرف',
    'english_name': 'Az-Zukhruf',
    'nuzool_location': 'Meccan',
    'nuzool_order': 63,
    'rukus': 7,
    'starting_aya': 4325,
    'total_ayas': 89,
    'translated_name': 'Ornaments of gold'},
    {'arabic_name': 'الدخان',
    'english_name': 'Ad-Dukhaan',
    'nuzool_location': 'Meccan',
    'nuzool_order': 64,
    'rukus': 3,
    'starting_aya': 4414,
    'total_ayas': 59,
    'translated_name': 'The Smoke'},
    {'arabic_name': 'الجاثية',
    'english_name': 'Al-Jaathiya',
    'nuzool_location': 'Meccan',
    'nuzool_order': 65,
    'rukus': 4,
    'starting_aya': 4473,
    'total_ayas': 37,
    'translated_name': 'Crouching'},
    {'arabic_name': 'الأحقاف',
    'english_name': 'Al-Ahqaf',
    'nuzool_location': 'Meccan',
    'nuzool_order': 66,
    'rukus': 4,
    'starting_aya': 4510,
    'total_ayas': 35,
    'translated_name': 'The Dunes'},
    {'arabic_name': 'محمد',
    'english_name': 'Muhammad',
    'nuzool_location': 'Medinan',
    'nuzool_order': 95,
    'rukus': 4,
    'starting_aya': 4545,
    'total_ayas': 38,
    'translated_name': 'Muhammad'},
    {'arabic_name': 'الفتح',
    'english_name': 'Al-Fath',
    'nuzool_location': 'Medinan',
    'nuzool_order': 111,
    'rukus': 4,
    'starting_aya': 4583,
    'total_ayas': 29,
    'translated_name': 'The Victory'},
    {'arabic_name': 'الحجرات',
    'english_name': 'Al-Hujuraat',
    'nuzool_location': 'Medinan',
    'nuzool_order': 106,
    'rukus': 2,
    'starting_aya': 4612,
    'total_ayas': 18,
    'translated_name': 'The Inner Apartments'},
    {'arabic_name': 'ق',
    'english_name': 'Qaaf',
    'nuzool_location': 'Meccan',
    'nuzool_order': 34,
    'rukus': 3,
    'starting_aya': 4630,
    'total_ayas': 45,
    'translated_name': 'The letter Qaaf'},
    {'arabic_name': 'الذاريات',
    'english_name': 'Adh-Dhaariyat',
    'nuzool_location': 'Meccan',
    'nuzool_order': 67,
    'rukus': 3,
    'starting_aya': 4675,
    'total_ayas': 60,
    'translated_name': 'The Winnowing Winds'},
    {'arabic_name': 'الطور',
    'english_name': 'At-Tur',
    'nuzool_location': 'Meccan',
    'nuzool_order': 76,
    'rukus': 2,
    'starting_aya': 4735,
    'total_ayas': 49,
    'translated_name': 'The Mount'},
    {'arabic_name': 'النجم',
    'english_name': 'An-Najm',
    'nuzool_location': 'Meccan',
    'nuzool_order': 23,
    'rukus': 3,
    'starting_aya': 4784,
    'total_ayas': 62,
    'translated_name': 'The Star'},
    {'arabic_name': 'القمر',
    'english_name': 'Al-Qamar',
    'nuzool_location': 'Meccan',
    'nuzool_order': 37,
    'rukus': 3,
    'starting_aya': 4846,
    'total_ayas': 55,
    'translated_name': 'The Moon'},
    {'arabic_name': 'الرحمن',
    'english_name': 'Ar-Rahmaan',
    'nuzool_location': 'Medinan',
    'nuzool_order': 97,
    'rukus': 3,
    'starting_aya': 4901,
    'total_ayas': 78,
    'translated_name': 'The Beneficent'},
    {'arabic_name': 'الواقعة',
    'english_name': 'Al-Waaqia',
    'nuzool_location': 'Meccan',
    'nuzool_order': 46,
    'rukus': 3,
    'starting_aya': 4979,
    'total_ayas': 96,
    'translated_name': 'The Inevitable'},
    {'arabic_name': 'الحديد',
    'english_name': 'Al-Hadid',
    'nuzool_location': 'Medinan',
    'nuzool_order': 94,
    'rukus': 4,
    'starting_aya': 5075,
    'total_ayas': 29,
    'translated_name': 'The Iron'},
    {'arabic_name': 'المجادلة',
    'english_name': 'Al-Mujaadila',
    'nuzool_location': 'Medinan',
    'nuzool_order': 105,
    'rukus': 3,
    'starting_aya': 5104,
    'total_ayas': 22,
    'translated_name': 'The Pleading Woman'},
    {'arabic_name': 'الحشر',
    'english_name': 'Al-Hashr',
    'nuzool_location': 'Medinan',
    'nuzool_order': 101,
    'rukus': 3,
    'starting_aya': 5126,
    'total_ayas': 24,
    'translated_name': 'The Exile'},
    {'arabic_name': 'الممتحنة',
    'english_name': 'Al-Mumtahana',
    'nuzool_location': 'Medinan',
    'nuzool_order': 91,
    'rukus': 2,
    'starting_aya': 5150,
    'total_ayas': 13,
    'translated_name': 'She that is to be examined'},
    {'arabic_name': 'الصف',
    'english_name': 'As-Saff',
    'nuzool_location': 'Medinan',
    'nuzool_order': 109,
    'rukus': 2,
    'starting_aya': 5163,
    'total_ayas': 14,
    'translated_name': 'The Ranks'},
    {'arabic_name': 'الجمعة',
    'english_name': "Al-Jumu'a",
    'nuzool_location': 'Medinan',
    'nuzool_order': 110,
    'rukus': 2,
    'starting_aya': 5177,
    'total_ayas': 11,
    'translated_name': 'Friday'},
    {'arabic_name': 'المنافقون',
    'english_name': 'Al-Munaafiqoon',
    'nuzool_location': 'Medinan',
    'nuzool_order': 104,
    'rukus': 2,
    'starting_aya': 5188,
    'total_ayas': 11,
    'translated_name': 'The Hypocrites'},
    {'arabic_name': 'التغابن',
    'english_name': 'At-Taghaabun',
    'nuzool_location': 'Medinan',
    'nuzool_order': 108,
    'rukus': 2,
    'starting_aya': 5199,
    'total_ayas': 18,
    'translated_name': 'Mutual Disillusion'},
    {'arabic_name': 'الطلاق',
    'english_name': 'At-Talaaq',
    'nuzool_location': 'Medinan',
    'nuzool_order': 99,
    'rukus': 2,
    'starting_aya': 5217,
    'total_ayas': 12,
    'translated_name': 'Divorce'},
    {'arabic_name': 'التحريم',
    'english_name': 'At-Tahrim',
    'nuzool_location': 'Medinan',
    'nuzool_order': 107,
    'rukus': 2,
    'starting_aya': 5229,
    'total_ayas': 12,
    'translated_name': 'The Prohibition'},
    {'arabic_name': 'الملك',
    'english_name': 'Al-Mulk',
    'nuzool_location': 'Meccan',
    'nuzool_order': 77,
    'rukus': 2,
    'starting_aya': 5241,
    'total_ayas': 30,
    'translated_name': 'The Sovereignty'},
    {'arabic_name': 'القلم',
    'english_name': 'Al-Qalam',
    'nuzool_location': 'Meccan',
    'nuzool_order': 2,
    'rukus': 2,
    'starting_aya': 5271,
    'total_ayas': 52,
    'translated_name': 'The Pen'},
    {'arabic_name': 'الحاقة',
    'english_name': 'Al-Haaqqa',
    'nuzool_location': 'Meccan',
    'nuzool_order': 78,
    'rukus': 2,
    'starting_aya': 5323,
    'total_ayas': 52,
    'translated_name': 'The Reality'},
    {'arabic_name': 'المعارج',
    'english_name': "Al-Ma'aarij",
    'nuzool_location': 'Meccan',
    'nuzool_order': 79,
    'rukus': 2,
    'starting_aya': 5375,
    'total_ayas': 44,
    'translated_name': 'The Ascending Stairways'},
    {'arabic_name': 'نوح',
    'english_name': 'Nooh',
    'nuzool_location': 'Meccan',
    'nuzool_order': 71,
    'rukus': 2,
    'starting_aya': 5419,
    'total_ayas': 28,
    'translated_name': 'Noah'},
    {'arabic_name': 'الجن',
    'english_name': 'Al-Jinn',
    'nuzool_location': 'Meccan',
    'nuzool_order': 40,
    'rukus': 2,
    'starting_aya': 5447,
    'total_ayas': 28,
    'translated_name': 'The Jinn'},
    {'arabic_name': 'المزمل',
    'english_name': 'Al-Muzzammil',
    'nuzool_location': 'Meccan',
    'nuzool_order': 3,
    'rukus': 2,
    'starting_aya': 5475,
    'total_ayas': 20,
    'translated_name': 'The Enshrouded One'},
    {'arabic_name': 'المدثر',
    'english_name': 'Al-Muddaththir',
    'nuzool_location': 'Meccan',
    'nuzool_order': 4,
    'rukus': 2,
    'starting_aya': 5495,
    'total_ayas': 56,
    'translated_name': 'The Cloaked One'},
    {'arabic_name': 'القيامة',
    'english_name': 'Al-Qiyaama',
    'nuzool_location': 'Meccan',
    'nuzool_order': 31,
    'rukus': 2,
    'starting_aya': 5551,
    'total_ayas': 40,
    'translated_name': 'The Resurrection'},
    {'arabic_name': 'الانسان',
    'english_name': 'Al-Insaan',
    'nuzool_location': 'Medinan',
    'nuzool_order': 98,
    'rukus': 2,
    'starting_aya': 5591,
    'total_ayas': 31,
    'translated_name': 'Man'},
    {'arabic_name': 'المرسلات',
    'english_name': 'Al-Mursalaat',
    'nuzool_location': 'Meccan',
    'nuzool_order': 33,
    'rukus': 2,
    'starting_aya': 5622,
    'total_ayas': 50,
    'translated_name': 'The Emissaries'},
    {'arabic_name': 'النبإ',
    'english_name': 'An-Naba',
    'nuzool_location': 'Meccan',
    'nuzool_order': 80,
    'rukus': 2,
    'starting_aya': 5672,
    'total_ayas': 40,
    'translated_name': 'The Announcement'},
    {'arabic_name': 'النازعات',
    'english_name': "An-Naazi'aat",
    'nuzool_location': 'Meccan',
    'nuzool_order': 81,
    'rukus': 2,
    'starting_aya': 5712,
    'total_ayas': 46,
    'translated_name': 'Those who drag forth'},
    {'arabic_name': 'عبس',
    'english_name': 'Abasa',
    'nuzool_location': 'Meccan',
    'nuzool_order': 24,
    'rukus': 1,
    'starting_aya': 5758,
    'total_ayas': 42,
    'translated_name': 'He frowned'},
    {'arabic_name': 'التكوير',
    'english_name': 'At-Takwir',
    'nuzool_location': 'Meccan',
    'nuzool_order': 7,
    'rukus': 1,
    'starting_aya': 5800,
    'total_ayas': 29,
    'translated_name': 'The Overthrowing'},
    {'arabic_name': 'الإنفطار',
    'english_name': 'Al-Infitaar',
    'nuzool_location': 'Meccan',
    'nuzool_order': 82,
    'rukus': 1,
    'starting_aya': 5829,
    'total_ayas': 19,
    'translated_name': 'The Cleaving'},
    {'arabic_name': 'المطففين',
    'english_name': 'Al-Mutaffifin',
    'nuzool_location': 'Meccan',
    'nuzool_order': 86,
    'rukus': 1,
    'starting_aya': 5848,
    'total_ayas': 36,
    'translated_name': 'Defrauding'},
    {'arabic_name': 'الإنشقاق',
    'english_name': 'Al-Inshiqaaq',
    'nuzool_location': 'Meccan',
    'nuzool_order': 83,
    'rukus': 1,
    'starting_aya': 5884,
    'total_ayas': 25,
    'translated_name': 'The Splitting Open'},
    {'arabic_name': 'البروج',
    'english_name': 'Al-Burooj',
    'nuzool_location': 'Meccan',
    'nuzool_order': 27,
    'rukus': 1,
    'starting_aya': 5909,
    'total_ayas': 22,
    'translated_name': 'The Constellations'},
    {'arabic_name': 'الطارق',
    'english_name': 'At-Taariq',
    'nuzool_location': 'Meccan',
    'nuzool_order': 36,
    'rukus': 1,
    'starting_aya': 5931,
    'total_ayas': 17,
    'translated_name': 'The Morning Star'},
    {'arabic_name': 'الأعلى',
    'english_name': "Al-A'laa",
    'nuzool_location': 'Meccan',
    'nuzool_order': 8,
    'rukus': 1,
    'starting_aya': 5948,
    'total_ayas': 19,
    'translated_name': 'The Most High'},
    {'arabic_name': 'الغاشية',
    'english_name': 'Al-Ghaashiya',
    'nuzool_location': 'Meccan',
    'nuzool_order': 68,
    'rukus': 1,
    'starting_aya': 5967,
    'total_ayas': 26,
    'translated_name': 'The Overwhelming'},
    {'arabic_name': 'الفجر',
    'english_name': 'Al-Fajr',
    'nuzool_location': 'Meccan',
    'nuzool_order': 10,
    'rukus': 1,
    'starting_aya': 5993,
    'total_ayas': 30,
    'translated_name': 'The Dawn'},
    {'arabic_name': 'البلد',
    'english_name': 'Al-Balad',
    'nuzool_location': 'Meccan',
    'nuzool_order': 35,
    'rukus': 1,
    'starting_aya': 6023,
    'total_ayas': 20,
    'translated_name': 'The City'},
    {'arabic_name': 'الشمس',
    'english_name': 'Ash-Shams',
    'nuzool_location': 'Meccan',
    'nuzool_order': 26,
    'rukus': 1,
    'starting_aya': 6043,
    'total_ayas': 15,
    'translated_name': 'The Sun'},
    {'arabic_name': 'الليل',
    'english_name': 'Al-Lail',
    'nuzool_location': 'Meccan',
    'nuzool_order': 9,
    'rukus': 1,
    'starting_aya': 6058,
    'total_ayas': 21,
    'translated_name': 'The Night'},
    {'arabic_name': 'الضحى',
    'english_name': 'Ad-Dhuhaa',
    'nuzool_location': 'Meccan',
    'nuzool_order': 11,
    'rukus': 1,
    'starting_aya': 6079,
    'total_ayas': 11,
    'translated_name': 'The Morning Hours'},
    {'arabic_name': 'الشرح',
    'english_name': 'Ash-Sharh',
    'nuzool_location': 'Meccan',
    'nuzool_order': 12,
    'rukus': 1,
    'starting_aya': 6090,
    'total_ayas': 8,
    'translated_name': 'The Consolation'},
    {'arabic_name': 'التين',
    'english_name': 'At-Tin',
    'nuzool_location': 'Meccan',
    'nuzool_order': 28,
    'rukus': 1,
    'starting_aya': 6098,
    'total_ayas': 8,
    'translated_name': 'The Fig'},
    {'arabic_name': 'العلق',
    'english_name': 'Al-Alaq',
    'nuzool_location': 'Meccan',
    'nuzool_order': 1,
    'rukus': 1,
    'starting_aya': 6106,
    'total_ayas': 19,
    'translated_name': 'The Clot'},
    {'arabic_name': 'القدر',
    'english_name': 'Al-Qadr',
    'nuzool_location': 'Meccan',
    'nuzool_order': 25,
    'rukus': 1,
    'starting_aya': 6125,
    'total_ayas': 5,
    'translated_name': 'The Power, Fate'},
    {'arabic_name': 'البينة',
    'english_name': 'Al-Bayyina',
    'nuzool_location': 'Medinan',
    'nuzool_order': 100,
    'rukus': 1,
    'starting_aya': 6130,
    'total_ayas': 8,
    'translated_name': 'The Evidence'},
    {'arabic_name': 'الزلزلة',
    'english_name': 'Az-Zalzala',
    'nuzool_location': 'Medinan',
    'nuzool_order': 93,
    'rukus': 1,
    'starting_aya': 6138,
    'total_ayas': 8,
    'translated_name': 'The Earthquake'},
    {'arabic_name': 'العاديات',
    'english_name': 'Al-Aadiyaat',
    'nuzool_location': 'Meccan',
    'nuzool_order': 14,
    'rukus': 1,
    'starting_aya': 6146,
    'total_ayas': 11,
    'translated_name': 'The Chargers'},
    {'arabic_name': 'القارعة',
    'english_name': "Al-Qaari'a",
    'nuzool_location': 'Meccan',
    'nuzool_order': 30,
    'rukus': 1,
    'starting_aya': 6157,
    'total_ayas': 11,
    'translated_name': 'The Calamity'},
    {'arabic_name': 'التكاثر',
    'english_name': 'At-Takaathur',
    'nuzool_location': 'Meccan',
    'nuzool_order': 16,
    'rukus': 1,
    'starting_aya': 6168,
    'total_ayas': 8,
    'translated_name': 'Competition'},
    {'arabic_name': 'العصر',
    'english_name': 'Al-Asr',
    'nuzool_location': 'Meccan',
    'nuzool_order': 13,
    'rukus': 1,
    'starting_aya': 6176,
    'total_ayas': 3,
    'translated_name': 'The Declining Day, Epoch'},
    {'arabic_name': 'الهمزة',
    'english_name': 'Al-Humaza',
    'nuzool_location': 'Meccan',
    'nuzool_order': 32,
    'rukus': 1,
    'starting_aya': 6179,
    'total_ayas': 9,
    'translated_name': 'The Traducer'},
    {'arabic_name': 'الفيل',
    'english_name': 'Al-Fil',
    'nuzool_location': 'Meccan',
    'nuzool_order': 19,
    'rukus': 1,
    'starting_aya': 6188,
    'total_ayas': 5,
    'translated_name': 'The Elephant'},
    {'arabic_name': 'قريش',
    'english_name': 'Quraish',
    'nuzool_location': 'Meccan',
    'nuzool_order': 29,
    'rukus': 1,
    'starting_aya': 6193,
    'total_ayas': 4,
    'translated_name': 'Quraysh'},
    {'arabic_name': 'الماعون',
    'english_name': "Al-Maa'un",
    'nuzool_location': 'Meccan',
    'nuzool_order': 17,
    'rukus': 1,
    'starting_aya': 6197,
    'total_ayas': 7,
    'translated_name': 'Almsgiving'},
    {'arabic_name': 'الكوثر',
    'english_name': 'Al-Kawthar',
    'nuzool_location': 'Meccan',
    'nuzool_order': 15,
    'rukus': 1,
    'starting_aya': 6204,
    'total_ayas': 3,
    'translated_name': 'Abundance'},
    {'arabic_name': 'الكافرون',
    'english_name': 'Al-Kaafiroon',
    'nuzool_location': 'Meccan',
    'nuzool_order': 18,
    'rukus': 1,
    'starting_aya': 6207,
    'total_ayas': 6,
    'translated_name': 'The Disbelievers'},
    {'arabic_name': 'النصر',
    'english_name': 'An-Nasr',
    'nuzool_location': 'Medinan',
    'nuzool_order': 114,
    'rukus': 1,
    'starting_aya': 6213,
    'total_ayas': 3,
    'translated_name': 'Divine Support'},
    {'arabic_name': 'المسد',
    'english_name': 'Al-Masad',
    'nuzool_location': 'Meccan',
    'nuzool_order': 6,
    'rukus': 1,
    'starting_aya': 6216,
    'total_ayas': 5,
    'translated_name': 'The Palm Fibre'},
    {'arabic_name': 'الإخلاص',
    'english_name': 'Al-Ikhlaas',
    'nuzool_location': 'Meccan',
    'nuzool_order': 22,
    'rukus': 1,
    'starting_aya': 6221,
    'total_ayas': 4,
    'translated_name': 'Sincerity'},
    {'arabic_name': 'الفلق',
    'english_name': 'Al-Falaq',
    'nuzool_location': 'Meccan',
    'nuzool_order': 20,
    'rukus': 1,
    'starting_aya': 6225,
    'total_ayas': 5,
    'translated_name': 'The Dawn'},
    {'arabic_name': 'الناس',
    'english_name': 'An-Naas',
    'nuzool_location': 'Meccan',
    'nuzool_order': 21,
    'rukus': 1,
    'starting_aya': 6230,
    'total_ayas': 6,
    'translated_name': 'Mankind'}
  ]